// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicTacToeRepository;

namespace TicTacToeRepository.Migrations
{
    [DbContext(typeof(TicTacToeDbContext))]
    [Migration("20220505114054_Room")]
    partial class Room
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TicTacToeDomain.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("MatchTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            MatchTime = new DateTime(2022, 5, 5, 13, 40, 53, 476, DateTimeKind.Local).AddTicks(9095),
                            Outcome = 2,
                            PlayerId = -1
                        });
                });

            modelBuilder.Entity("TicTacToeDomain.PlayerRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("FirstPlayer")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SecondPlayer")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PlayerRoom");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            FirstPlayer = -1,
                            Name = "room1",
                            SecondPlayer = -1
                        });
                });

            modelBuilder.Entity("TicTacToeDomain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "mkisic99@gmail.com",
                            Name = "Mihajlo",
                            Password = "ftn",
                            Surname = "Kisic",
                            Username = "mkisic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
